/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SwingTT;

/**
 *
 * @author Dell
 */
public class javaSwing6 extends javax.swing.JFrame {

    /**
     * Creates new form javaSwing04
     */
    static int dem = 1;
    public javaSwing6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HAjLabel1 = new javax.swing.JLabel();
        AHAjLabel2 = new javax.swing.JLabel();
        HienThiJLabel1 = new javax.swing.JLabel();
        okjButton1 = new javax.swing.JButton();
        HinhAnhjLabel1 = new javax.swing.JLabel();
        HienHinhAnhjButton1 = new javax.swing.JButton();
        AnHinhAnhjButton2 = new javax.swing.JButton();

        HAjLabel1.setText("Hien thi hinh anh");

        AHAjLabel2.setText("An hinh anh");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HienThiJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HienThiJLabel1.setText("Ban da click nut ok 1 lan!");

        okjButton1.setText("Ok");
        okjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okjButton1ActionPerformed(evt);
            }
        });

        HinhAnhjLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\1ab17dada4e869b630f9.jpg")); // NOI18N
        HinhAnhjLabel1.setText("Hinh Anh");
        HinhAnhjLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HinhAnhjLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        HienHinhAnhjButton1.setText("Hien hinh anh");
        HienHinhAnhjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HienHinhAnhjButton1ActionPerformed(evt);
            }
        });

        AnHinhAnhjButton2.setText("An hinh anh");
        AnHinhAnhjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnHinhAnhjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(HienHinhAnhjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AnHinhAnhjButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(HinhAnhjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(okjButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HienThiJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HienThiJLabel1)
                    .addComponent(okjButton1))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HienHinhAnhjButton1)
                    .addComponent(AnHinhAnhjButton2))
                .addGap(51, 51, 51)
                .addComponent(HinhAnhjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okjButton1ActionPerformed
        // TODO add your handling code here:
        
        HienThiJLabel1.setText("Ban da click nut ok "+dem + " lan");
        dem++;
    }//GEN-LAST:event_okjButton1ActionPerformed

    private void HienHinhAnhjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HienHinhAnhjButton1ActionPerformed
        // TODO add your handling code here:
        HinhAnhjLabel1.setVisible(true);
    }//GEN-LAST:event_HienHinhAnhjButton1ActionPerformed

    private void AnHinhAnhjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnHinhAnhjButton2ActionPerformed
        // TODO add your handling code here:
        HinhAnhjLabel1.setVisible(false);
    }//GEN-LAST:event_AnHinhAnhjButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(javaSwing6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(javaSwing6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(javaSwing6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(javaSwing6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new javaSwing6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AHAjLabel2;
    private javax.swing.JButton AnHinhAnhjButton2;
    private javax.swing.JLabel HAjLabel1;
    private javax.swing.JButton HienHinhAnhjButton1;
    private javax.swing.JLabel HienThiJLabel1;
    private javax.swing.JLabel HinhAnhjLabel1;
    private javax.swing.JButton okjButton1;
    // End of variables declaration//GEN-END:variables
}
